name: fav_button
description: favorite_button is a flutter library that allows you to create custom favorite featured buttons with animation effects too.
version: 0.0.1
homepage: https://github.com/omarnasser199789/favorite_button


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
